### ISSUE TITLE
Green tiles everywhere 

### ISSUE THREAD

**Issue by Dennis98BE** [kubilus1/autoortho#283]
Please help

It's not only at Starsim KPHL I've had this. I really wish someone can help me solve what's going on. 

https://gyazo.com/ebadb76099c4ed625fb898d2b6ef7df9

[Log.txt](https://github.com/kubilus1/autoortho/files/12137460/Log.txt)

**Comment by dpdurst** [comment]
There is nothing to fix from the standpoint of AutoOrtho, this is what happens when the scenery is not being streamed from the server side for whatever reason. This is something we all get, its more apparent with faster flying aircraft than slower SEL or MEL. The only thing you can try is to increase the max_wait time in the autoortho configuration file and see if this helps.

**Comment by Dennis98BE** [comment]
I increasd the waiting time to 1.0 and the green tiles are gone but look at this? https://gyazo.com/d972ff989c0c50da93713044e1a4c38b

What can I do about that? Thank you

**Comment by Dennis98BE** [comment]
Literally my whole 40 min flight is blurry. My DL speed is 700mb/s

**Comment by dpdurst** [comment]
https://github.com/kubilus1/autoortho/discussions/284
