### ISSUE TITLE
Using AutoOrtho with WinFSP makes X-plane rearranging sceneries order so ortho maps are always placed at the top

### ISSUE THREAD

**Issue by alexmaryin** [kubilus1/autoortho#356]
As Dokan doesn't properly works in my Win 11 I use WinFSP. AutoOrtho starts well, but X-plane on each start rearranges the order in scenery_packs.ini, so z_ao_... files are placed at the top. Of course any airport doesn't visible after loading, only orto quads even on the airport place.

**(please complete the following information):**
 - OS: Windows 11
 - XPlane Version: XP12.06b7
 - AutoOrtho Version 0.5.1-3
 - Filesystem type NTFS
 
![X-System 28 08 2023 19_47_22](https://github.com/kubilus1/autoortho/assets/74375962/f7c7c0d2-860e-49c6-92fa-ab0b68e1c0ca)

**Comment by marloscaida** [comment]
Alex:
Reorder your scenery_pack.ini, save it with the lines in the correct order, after that go to the file properties and set the read-only flag. That way you'll get a nifty warning that XP couldn't edit your scenery_pack.ini file and won't be able to alter the order you've given it.
To avoid surprises, launch XP and with XP loaded, that is, at the moment you see the plane and your preferred airport, copy and paste the scenery_pack.ini file elsewhere, then reorder it, save it, make it read-only , and copy it back into your Custom Scenery folder. voila!
Regards
carlos

**Comment by alexmaryin** [comment]
Carlos, I've tried this way too. It didn't work for me. First, xplane can't inject a link for SAM plugin (I have no idea why it doesn't work in regular way with SAM), Second, it's even can't be loaded at airport successfully.

**Comment by marloscaida** [comment]
Alex:

You have two paths for the SAM plugin. One, is that I add it manually. The second is the following:
1. Forget AO. Roll XP and wait to see your preferred aircraft landed at the airport of your choice.
2.- Go to the Custom Scenery folder and copy the scenery_pack.ini file in My Documents or in the folder you want.
3.- Edit the scenery_pack.ini file that you copied to My Documents with Notepad.
4.- Verify that the SAM lines are located above. You should see something more or less like this:

1000Version
SCENERY

SCENERY_PACK C:\Program Files (x86)\Steam\steamapps\common\X-Plane 12\Resources\plugins\SAM\lib\SAM_GlobalTrees/
SCENERY_PACK C:\Program Files (x86)\Steam\steamapps\common\X-Plane 12\Resources\plugins\SAM\lib\SAM_Library/
SCENERY_PACK C:\Program Files (x86)\Steam\steamapps\common\X-Plane 12\Resources\plugins\SAM\lib\SAM_Seasons/
SCENERY_PACK Custom Scenery/SAM_DeveloperPack/
(if they are not, add them by hand....)

5.- Add the lines corresponding to AO at the end of the scenery_pack.ini so that they look like this:

SCENERY_PACK Custom Scenery/yAutoOrtho_Overlays/
SCENERY_PACK Custom Scenery/z_ao_sa/
SCENERY_PACK Custom Scenery/z_autoortho/
(change the middle line according to your own AO)

6.- Save the file scenery_pack.ini
7.- Open it again to see that everything is in order and there was no mistake.
8.- Turn off the x-plane.
9.- Copy the newly edited file to the Custom Scenery folder (you should ask to rewrite it. If you don't, we have a problem...)
10.- Hover over scenery_pack.ini and with the right mouse button, open the contextual menu. Go to properties, then mark it as read-only.
11.- Now if you run the AO and wait for the whole process to be completed and the waiting lines to start the simulator again.
12.- X-plane will show you a warning telling you that scenery_pack.ini is read-only (if it doesn't, close the simulator and follow these instructions again...)
If you show it to him, he should be able to see his preferred aircraft sitting at the airport of his choice.

I hope these brief instructions will help you.

Regards
carlos

**Comment by marloscaida** [comment]
Alex:

I understand. The same thing happens to a friend. The problem is the processing capacity of your machine (I'm talking about processor, motherboard, and processor). Against that there is not much to do.
In the first moments, I opened AO and the simulator in each of the airports in which I operate so that it would generate the AO environments. That helped me a lot. But I also had those problems until I managed to cover practically all of South America. It has taken me several hours of flight.

Regards
carlos

**Comment by marloscaida** [comment]
Alex, 
Sincerely I dont know. My friend has a great AMD processor and a killer AMD graphics card, but he has an old motherboard that bottlenecks data transfer. He is going through the same thing as you. I can't help you more than that. It really is disappointing.
regards
carlos

**Comment by alexmaryin** [comment]
Anyway, thank you for your help. I think I will back to AutoOrtho in future, when it become more stable and lightweight.

**Comment by Dyno744** [comment]
Hi there, I was having the same problem and searched this up. Turns out, this seems to have been rectified with the newest release (I haven't actually tested it yet, but the release notes specify so): https://github.com/kubilus1/autoortho/releases/tag/0.6.1

"This version will attempt to restore a placeholder set of dirs for each scenery installed when the program is shutdown. This should help keep the order of scenery_pack.ini intact when users run X-Plane without AO running."

Hope this helps.

**Comment by marloscaida** [comment]
I am using the "unstable" version that will be released soon with a new number. And, the truth is, it's going very well.
I downloaded it from here:

https://github.com/kubilus1/autoortho/releases/download/unstable/autoortho_win_unstable.zip

The technique is to open the sim until the window appears where you choose the airport and the aircraft.
Then, AO is executed, until the test is performed. If everything goes ok, continue with the sim.
It works very well.

Regards
carlos
