### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Awemeter** [kubilus1/autoortho#36]
Auto ortho is using 10-30% of my CPU during flight. 
![image](https://user-images.githubusercontent.com/71922517/212485467-11e8d27b-99e8-4bd6-95b0-7addb43d1d35.png)

**Comment by ivotaHR** [comment]
![1234](https://user-images.githubusercontent.com/96768739/212486921-2ce57b60-c354-4d01-bcc5-d5675194d5d2.png)

**Comment by Awemeter** [comment]
Idk why it's so bad for me. I have tried a reinstalling of python, winfsp, and autoortho.

**Comment by kubilus1** [comment]
The CPU usage during flight will vary depending on the power of your CPU quite a bit.  Processing the images during flight can take a bit of CPU.  10-30% doesn't sound unreasonable.  What CPU do you have?

**Comment by Awemeter** [comment]
> The CPU usage during flight will vary depending on the power of your CPU quite a bit. Processing the images during flight can take a bit of CPU. 10-30% doesn't sound unreasonable. What CPU do you have?

i9-9900k

**Comment by Awemeter** [comment]
Also I have 4 proccess running which are python, python 32, cmd and cmd conhost while the person above had 2 is that normal?

**Comment by kubilus1** [comment]
I typically run on Linux, so can't really compare, but I'll look next time I test on my Windows setup.  But I think what you are seeing is normal.  From the looks of it, that other example looks to be when it is idle.

**Comment by beaufortuk** [comment]
Hey, I'm having very high CPU spikes on my rig, which are bad enough to keep disconnecting from VATSIM. Then it settles down again nicely (for 5 mins). At the time both autoortho and X-Plane have high CPU, as though some hand-off is consuming the CPU. 

During the spike (disconnects from VATSIM due to low fps):
![Screenshot 2023-04-23 195123](https://user-images.githubusercontent.com/80645398/233859341-9bdad77f-2db3-4f0b-bb69-2f6284d6e4b5.png)

Post-spike:
![Screenshot 2023-04-23 195248](https://user-images.githubusercontent.com/80645398/233859378-b372a23a-f7cf-4c0b-b068-56bd3693b9d6.png)

I love this project and am very happy to help with any troubleshooting, let me know.
