### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by airbusseventhreeseven** [kubilus1/autoortho#371]
Okay, so a while back I pointed out the performance of this plugin, and got told to wait for 12.06. Well the release of 12.06 has come and gone, and the stutters remain. Overall fps is higher, which tells me LR did something, so I am highly suspect this plug-in is the issue. It’s a great one, but I would love to see some performance improvements in the near future.

**Comment by Awemeter** [comment]
I also have a problem with performance. 80% of the time fps is in the 30s or 40s but for some reason, it drops to 20fps for 30-60 seconds. I suspect it has something to do with new tiles being loaded.

**Comment by Awemeter** [comment]
This issue is still present in V0.7.1 with X-Plane 12.07  and X-Plane 12.08-Beta-1.

**Comment by tzimpel** [comment]
Not only does the frame rate drop, also ATC becomes extremely laggy or even unresponsive for a minute or even longer (had it for 3-4 minutes lately.

Tested on 12.0.8-rc3

**Comment by loganlaporte** [comment]
Im in the same boat at @tzimpel I think. The issue has persisted since 0.5 which I just attributed to the newness of program. 
The biggest annoyance I have is what I call the last 2000ft. On final into an airport and frames just take a dump because I assume its rendering new tiles. Need the program render new tiles/ distance based on speed/ alt.
