### ISSUE TITLE
AutoOrtho 0.7.0 causing X-Plane 12 on Linux to crash during flight

### ISSUE THREAD

**Issue by helixcraig** [kubilus1/autoortho#440]
Have been experiencing X-Plane 12 crashing (on Linux OS) with AutoOrtho since version 0.6.0
To reproduce:
Create flight in any Airliner (I used several, Zibo, Default A330, SSG 747 etc) from YBBN to YMML with Apac scenery.
I am on OS Linux Mint 21.2.
My system has plenty of GPU and CPU and network speeds to handle demand. I will attach log files and screen shots to assist.
Important to note I disabled all X-Plane plug-ins 1 by 1 and removed all the X-World 3.0 scenery before isolating AutoOrtho as the problem. 
I experienced this issue on 0.6.0 Auto Ortho, X-Plane crashed on 9 out of 10 flights, mid-flight.
I rolled back to 0.4.4 AutoOrtho, and did not experience the issue. Many flights completed without crash.
I recently updated to 0.7.0 AutoOrtho, and am now experiencing the issue again. So far tried 5 test flights. All but one has crashed mid-flight.

System Info:
OS - Linux Mint 21.2 Cinnamon
Linux Kernel: 5.15.0-87-generic
X-Plane version 12.07
System memory: 32Gb
GPU: NVIDIA GeForce RTX 2080 Ti
CPU: AMD Ryzen 7 5700G 

[system_info.txt](https://github.com/kubilus1/autoortho/files/13195571/system_info.txt)
[autoortho-1.log](https://github.com/kubilus1/autoortho/files/13195573/autoortho-1.log)
[autoortho-2.log](https://github.com/kubilus1/autoortho/files/13195574/autoortho-2.log)
[Log-1.txt](https://github.com/kubilus1/autoortho/files/13195575/Log-1.txt)
[Log-2.txt](https://github.com/kubilus1/autoortho/files/13195576/Log-2.txt)
![Screenshot from 2023-10-28 19-40-49](https://github.com/kubilus1/autoortho/assets/94152727/d6a11fce-36ce-41d4-bb12-a481f51c4004)

**Comment by helixcraig** [comment]
Any update on this issue? Thanks.

**Comment by hawajka76** [comment]
I'm also encountering this issue with 0.7.1 on linux. Version 0.4.x was stable.

**Comment by SaturnV62653** [comment]
Also seem to be having this issue. Seems to be fine during preflight, but if i am flying anywhere or going fast (ex. takeoff roll) it seems to crash pretty quickly. I think it might be an issue loading tiles. It worked perfectly fine before I updated to a new version

**Comment by ivaradi** [comment]
I have also encountered this issue. 

It seems, that turning off FUSE threading alleviates the problem: open the ~/.autoortho file in a text editor. It should contain a section like this:

```
[fuse]
# enable or disable multi-threading when using fuse
threading = True
```

Change the True to False and the crashes will probably disappear.

@kubilus1 the functions of the `AutoOrtho` class in `autoortho_fuse.py` should contain some kind of locking. On my system X-Plane crashed in the DSFMemRead function, because the DSF data read was corrupted. When a DSF is being read, the `read()` function is called repeatedly, potentially in parallel from multiple threads. There is a race condition in this code part:

```
        if not data:
            os.lseek(fh, offset, os.SEEK_SET)
            data = os.read(fh, length)
```
Two or more threads executing it simultaneously can, for example, run the `lseek()` calls first, resulting in a file offset requested by a random one of them, and the following read would read from a place different from what was intended. It can be easily tested by `cat`'ing a larger DSF file into `md5sum`, and you can often get different checksums for different runs. I think maybe a lock for each file handle could work (depending on how many files are kept open simultaneously, but probably not many, as X-Plane opens them, reads them and closes them), or the file handles could be `dup()`'ed for each thread where they are accessed from (e.g. on demand for a thread when it is first access from that thread).

**Comment by SaturnV62653** [comment]
I tried multiple times with the FUSE multi-threading at false, but to no avail. Still crashing midflight

**Comment by kubilus1** [comment]
> I have also encountered this issue.
> 
> It seems, that turning off FUSE threading alleviates the problem: open the ~/.autoortho file in a text editor. It should contain a section like this:
> 
> ```
> [fuse]
> # enable or disable multi-threading when using fuse
> threading = True
> ```
> 
> Change the True to False and the crashes will probably disappear.
> 
> @kubilus1 the functions of the `AutoOrtho` class in `autoortho_fuse.py` should contain some kind of locking. On my system X-Plane crashed in the DSFMemRead function, because the DSF data read was corrupted. When a DSF is being read, the `read()` function is called repeatedly, potentially in parallel from multiple threads. There is a race condition in this code part:
> 
> ```
>         if not data:
>             os.lseek(fh, offset, os.SEEK_SET)
>             data = os.read(fh, length)
> ```
> 
> Two or more threads executing it simultaneously can, for example, run the `lseek()` calls first, resulting in a file offset requested by a random one of them, and the following read would read from a place different from what was intended. It can be easily tested by `cat`'ing a larger DSF file into `md5sum`, and you can often get different checksums for different runs. I think maybe a lock for each file handle could work (depending on how many files are kept open simultaneously, but probably not many, as X-Plane opens them, reads them and closes them), or the file handles could be `dup()`'ed for each thread where they are accessed from (e.g. on demand for a thread when it is first access from that thread).
> 
> **Edit**: I was wrong about `dup()`'ing, since the offset is shared between the file descriptor copies. However, there is the `os.pread()` function (wrapping the `pread` system call), which can be given an offset and does not care about or modify the file handle's offset. So it is perfect for this use-case.

Yeah I think you have a good point.  Locking for the fuse layer stuff needs to be handled very carefully or perf gets tanked, but there are ways to handle that.  I'll look into `pread` as well.

**Comment by kubilus1** [comment]
Unfortunately it does look like pread is Unix only so this would continue to be an issue for Windows users.

**Comment by kubilus1** [comment]
Try the latest 'unstable' build, that should resolve the DSF checksum issue anyhow.  https://github.com/kubilus1/autoortho/releases/tag/unstable

**Comment by helixcraig** [comment]
Thanks @kubilus1 I will test next week when I am back in front of the computer.

**Comment by kubilus1** [comment]
Latest changes should mitigate, if not fix this issue.
