### ISSUE TITLE
AO keeps  freezing after 30min of flight

### ISSUE THREAD

**Issue by c777alpha** [kubilus1/autoortho#521]
AO 7.2 keeps freezing after 30min of flight from any airport...I was flying the FF767   and the toliss 320....I have upgraded to WIN11 with all win updates....using xp12.1.0 b5....I have the latest Nvidia drivers.....and have updated all my aircraft...I have attached my log text file  ...Thank you

**To Reproduce**

**Expected behavior**

**Screenshots**

**(please complete the following information):**
 - OS: [e.g. Windows 11]
 - XPlane Version: [e.g. XP12.1.0 beta5]
 - AutoOrtho Version [e.g. 0.7.2]
 - Filesystem type (NTFS, exFAT, etc)

**Additional context**
[Log.txt](https://github.com/user-attachments/files/15522775/Log.txt)

**Comment by CabrioletDiskette** [comment]
I am having a similar error on X-Plane 12.1.0 but beta 6. My OS is also Linux(updated Debian testing, kernel 6.7.12 with NVIDIA drivers) if that is helpful. I thought it might be an internet speed thing because it would "catch up" after a few minutes but would then freeze again. Similar to @c777alpha it occurred 30 minutes into the flight. I have had no other issues until this version of X-Plane.

Log attached, I will also send an autoortho log too when I get a chance(IE output from terminal)
[Log.txt](https://github.com/user-attachments/files/15711569/Log.txt)

**Comment by MarcusGama** [comment]
I'm having this issue also.
A wrote a full report on X-Plane.org forum.

https://forums.x-plane.org/index.php?/forums/topic/310630-autoortho-072-freezing-on-linux-x-plane-1210-rc2/
