### ISSUE TITLE
Trees On airport

### ISSUE THREAD

**Issue by rcfullscale** [kubilus1/autoortho#550]
there appear to be trees on some airports covering parts of the airport. taxiways, runways, etc

I've found the issue at ybbn and ybsu

![Screenshot 2024-11-08 171638](https://github.com/user-attachments/assets/26f08582-4375-4e68-a5e2-7d642b3d2ff8)

**(please complete the following information):**
Windows 11
XP12.1.2
0.4.3
 I've reinstalled and played with the scenery.ini lots with no joy

**Comment by jayeye2011** [comment]
That is because the current version of autoortho was developed for X-Plane 11 and uses the X-Plane 11 Global Scenery data and not X-Plane 12 Global Scenery data. I also suspect that he is not using the alpha version of Ortho4XP that is supposed to support the scenery features added by X-Plane 12.  So what  you are seeing is where trees would be in X-Plane 11. Also X-Plane 11's terrain elevation mesh data is not the same as X-Plane 12's so you can run into the situation that certain airfield runways have massive bumps in them. Also you will not see trees change colors based on seasons or hear birds in forests or see the water enhancements that X-Plane 12 introduced. The roads and building positioning is also based on X-Plane 11's so this will deviate from that provided by X-Plane 12. I really hope that the author of this addon will make a version specifically for X-Plane 12 but since he seems to not be very active anymore, I suspect that is not going to happen.

Here is an example of UT75 in X-Plane 11 with AutoOrtho
![20241115031655_1](https://github.com/user-attachments/assets/c8777a0e-6f6a-40c1-8217-2cbdb00ba371)

UT75 in X-Plane 12 in AutoOrtho
![20241115032114_1](https://github.com/user-attachments/assets/e33641c1-75f8-4fb3-914a-943847012f17)
 
Edit: I guess I am somewhat wrong regarding tree placement after all with respect to which is providing the tree data. But obviously there is some difference in tree placement between 11 and 12 no matter which sim's data is being used.

Edit 2: Here is UT75 in X-Plane 12 without AutoOrtho, just the vanilla game Global Scenery. As you can see no trees on the runway. So I don't know what caused the trees to be introduced since neither X-Plane 11 UT75 or X-Plane 12 UT75 has them. So maybe this is a true bug that need to be fixed after all.
![20241115033113_1](https://github.com/user-attachments/assets/d92ec1ed-a135-4dff-9ad3-17977993fa3e)

Edit 2: Here is UT75 in X-Plane 12 without AutoOrtho, just the vanilla game Global Scenery. As you can see no trees on the runway. So I don't know what caused the trees to be introduced since neither X-Plane 11 UT75 or X-Plane 12 UT75 has them. So maybe this is a true bug that need to be fixed after all.
![20241115033113_1](https://github.com/user-attachments/assets/ac5dbd51-cfc5-4f80-9b1c-9578830ceac1)
